### ISSUE TITLE
Restrukturierung "Publikationen (DE)"

### ISSUE THREAD

**Issue by STruckenbrodt** [fieldmapp/fieldmapp.github.io#3]
Darstellungen unter "Publikationen", die, wenn möglich, noch angepasst werden sollen.
@BMI24 : Wenn du Zeit hast, fände ich es schön, wenn du mir kurz erklären könntest, wie man die aufgelisteten Anpassungen vornehmen kann (eilt nicht). Dann muss ich dich das nächste Mal (hoffentlich) nicht mehr behelligen.

## Todos
- [x] Entfernen Doppelstruktur unter "Themenspezifische Publikationen"
- [x] Entfernen Doppelstruktur unter "Themenverwandte Publikationen"
- [x] Inhalt der "Describtion" in der Kurz-Vorschau (Eingeklapptes Menü zu "Themenspezifische Publikationen" bzw.  "Themenverwandte Publikationen") anzeigen oder nur Überschriften, die auf der vollen Seite gelistet sind
- [x] Anzeigen der Überschriften z.B. unter "Themenspezifische Publikationen" im Inhaltsverzeichnis auf der linken Seite (rechts erscheinen diese bereits)

**Comment by BMI24** [comment]
Ich hatte für die Publikations-Seite den Blog-Stil (siehe https://www.docsy.dev/docs/adding-content/content/#content-sections-and-templates )  festgelegt. Das kann man in der Datei [/content/de/publications/_index.md](https://github.com/fieldmapp/fieldmapp.github.io/blob/master/content/de/publications/_index.md) in Zeile 10 ändern. Meine Vermutung war, dass du da für neue Publikationen einen neuen Blog-Post erstellen willst. Aktuell sieht es aber mehr danach aus, als ob eine Seite im Wiki-Stil besser passen würden. Denkst du das auch?

**Comment by STruckenbrodt** [comment]
Ja, ich denke der Wiki-Stil wäre geeigneter. (Der Blog-Stil sollte für "News" passend sein.) 
Ich habe gerade versucht, den Blog-Stil auf den des Wikis abzuwandeln. Einmal in dem ich die Zeile 10 von "blog" aucf "docs" veändert habe, was dazu geführt hat, dass der Inhalt der "Themenspezifischen Publikationen" nicht mehr über die Website erreichbar war. Anschließend habe ich es versucht, in dem ich die Formatierung der "_index.md" vom Wiki übernommen habe. Daraufhin war der gesamte Inhalt unter "Publikationen" weg. Kannst du mir helfen, zu verstehen, was ich falsch gemacht habe? (Vorallem ist mir unklar, warum der letzte Änderungsversuch nicht erfolgreich war.) Sorry, für all die doofen Fragen...

**Comment by BMI24** [comment]
Absolut kein Problem! Ich lag auch nicht richtig, tatsächlich muss man sowohl Zeile 10 als auch 4 verändern. Jetzt sieht es gut aus. 
Um die Doppelstruktur zu entfernen würde ich den Inhalt aus den jeweiligen post1.md Dateien in ihre _index.md verschieben.
Wenn du willst, dass die einzelnen Überschriften auch links in der Navigation auftauchen, könnte man jede Überschrift mit Inhalt auch einfach in eine eigene Seite packen. Wenn du das nicht willst, müsste ich mal schauen ob man auch Überschriften aus den Seiten in der Navigation links anzeigen kann.

**Comment by STruckenbrodt** [comment]
Vielen Dank für seine Hinweise. Ich habe den Inhalt der post1.md in die _index.md verschoben, da ich mehrere Unterseiten bisher etwas übertrieben fände. Kann man vllt. später mal machen, wenn die Publikationslisten über voll sind. ;-)
